name: suo
description: suo library for store documents in your swamp
version: 0.3.1

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  path: ^1.7.0

dev_dependencies:
  #path: ^1.7.0
  watcher: 0.9.7+15
  pedantic: ^1.8.0
  test: ^1.6.0
