targets:
  $default:
    builders:
      suo_generator|suo:
        enabled: true

builders:
  index:
    target: ":suo_generator"
    import: "package:suo_generator/builder.dart"
    builder_factories: ["indexBuilder"]
    build_extensions: {".dart": [".suo_generator.idx.part"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
    