name: suo_generator
description: A starting point for Dart libraries or applications.

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  build: ^2.1.1
  source_gen: ^1.1.1
  code_builder: ^4.1.0
  path: ^1.8.0

  suo:
    path: ../suo

dev_dependencies:
  build_test: ^2.1.4
  build_runner: ^2.1.4
  test: ^1.19.3
