name: suo_generator
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  build: ^1.3.0
  source_gen: ^0.9.6
  code_builder: ^3.4.1
  path: ^1.7.0

  suo:
    path: ../suo

dependency_overrides:
  analyzer: '0.39.14'

dev_dependencies:
  build_test: ^1.0.0
  build_runner: ^1.10.1
  test: ^1.15.3
