name: suo_generator
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.0.2
  source_gen: ^1.0.1
  code_builder: ^4.0.0
  path: ^1.8.0

  suo:
    path: ../suo

dev_dependencies:
  build_test: ^2.1.0
  build_runner: ^2.0.4
  test: ^1.17.7
