name: simple_example
description: A sample usage of suo and suo_generator packages.


environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  path: ^1.7.0
  suo:
    path: ../suo

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: 
  build_verify: 
  suo_generator:
    path: ../suo_generator
